version: '3.7'

services:
  redis:
    restart: always
    image: redis:6
    container_name: platon_redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - platon-network
 
  postgres:
    restart: always
    image: postgres:13
    container_name: platon_postgres
    ports:
      - 5431:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - platon-network
    env_file:
      - .env

  api:
    restart: always
    build:
      context: ../
      dockerfile: platon/api/Dockerfile
    image: platon/api
    container_name: platon_api
    command: sh -c "python3 manage.py waitdb &&
                    python3 manage.py migrate &&
                    python3 manage.py createdefaults &&
                    python3 manage.py collectstatic --noinput &&
                    python3 manage.py runserver 0.0.0.0:8000 &&
                    uvicorn platon.asgi:application --port 8000 --host 0.0.0.0 --workers 1"
    ports:
      - 8000
    volumes:
      - media:/api/media
      - static:/api/static
    networks:
      - platon-network
    environment:
      - 'SANDBOX_URL=http://$SANDBOX_HOST:$SANDBOX_PORT'
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    #  - elasticsearch

  server:
    restart: always
    build:
      context: ../
      dockerfile: platon/server/Dockerfile.prod
    image: platon/server
    container_name: platon_server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"    
    ports:
      - 80:80
      - 443:433
    volumes:
      # DJANGO
      - media:/api/media
      - static:/api/static

      # NGINX CONF
      - ./server/nginx.prod.conf:/etc/nginx/nginx.conf
     
      # SSL CONF
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot

    networks:
      - platon-network
    links:
      - api:api
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
        - ./server/certbot/conf:/etc/letsencrypt
        - ./server/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do cerbot renew; sleep 12h & wait $${!}; done;'"
   
  celery:
    restart: always
    image: platon/api
    container_name: platon_celery
    command: celery -A platon worker --beat --scheduler django -l info --uid=nobody --gid=nogroup
    volumes:
      - ../platon-server/:/api
    networks:
      - platon-network
    env_file:
      - .env
    depends_on:
      - api
      - redis
      - postgres

  # elasticsearch:
  #   restart: always
  #   image: elasticsearch:7.12.0
  #   container_name: platon_elasticsearch
  #   ports:
  #     - 9200
  #     - 9300
  #   volumes:
  #     - elasticsearchdata:/usr/share/elasticsearch/data
  #   networks:
  #     - platon-network
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms750m -Xmx750m


volumes:
  media:
  static:
  redisdata:
  postgresdata:
  #elasticsearchdata:


networks:
  platon-network:
    driver: bridge